FROM ubuntu:latest
MAINTAINER Devesh Bajaj "deveshbajaj59@gmailcom"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]
